name: dbt_project
version: 1.0.0
config-version: 2

profile: dbt_project  

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
packages-install-path: "dbt_packages"
clean-targets: ["target", "dbt_packages"]

models:
  +materialized: view
