name: dbt_itay
version: 1.0.0
config-version: 2

profile: dbt_project  

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store SQL files
packages-install-path: "dbt_packages"
clean-targets: ["target", "dbt_packages"] # directions to be removed by 'dbt clean'

models:
  dbt_itay:
    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral

 